- hosts: vsd
  sudo: yes
  gather_facts: no
  vars:
    vsd_iso: /home/centos/nuage-files/VSD-c67-4.0.2_9.iso
  roles:
    - nuage-vsd-installer

  tasks:

    - name: Add Port-Forwarding Firewall rules
      shell: "iptables -t nat -A PREROUTING -i eth0 -p tcp --dport {{ item.incport }} -j DNAT --to {{ item.host }}:{{ item.destport }} ; \
              iptables -A FORWARD -i eth0 -p tcp --dport {{ item.destport }} -d {{ item.host }} -j ACCEPT"
      with_items:
        - { host: "{{ inventory_hostname }}", incport: 8443, destport: 8443 }
      delegate_to: "{{ gatewayip }}"
     
    - name: Save Firewall rules
      shell: "iptables-save > /etc/sysconfig/iptables"
      delegate_to: "{{ gatewayip }}"
