---
- hosts: localhost 
  gather_facts: False 


  tasks:
    - name: Deploy VSD VM on EC2
      ec2:
       key_name: "{{ aws.sshkey }}"
       instance_type: m3.xlarge
       image: ami-8997afe0
       wait: yes
       group: default
       count: 1
       region: "{{ aws.region }}"
       volumes:
        - device_name: /dev/sda
          volume_size: 100
          delete_on_termination: True
       vpc_subnet_id: "{{ vsd.subnet }}"
       instance_tags:
        Name: vsd
      register: ec2

    - name: Add new instance to host group
      add_host: name={{ item.private_ip }} dnshostname={{ item.private_ip }} groupname=vsd ansible_ssh_user=root
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    - name: Deploy VSC Host VM on EC2
      ec2:
       key_name: "{{ aws.sshkey }}"
       instance_type: t2.large
       image: ami-6d1c2007
       wait: yes
       group: default
       count: 1
       region: "{{ aws.region }}"
       vpc_subnet_id: "{{ vsd.subnet }}"
       instance_tags:
        Name: vschost
      register: ec2

    - name: Add new instance to host group
      add_host: name={{ item.private_ip }} dnshostname={{ item.private_ip }} groupname=vschost
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    - debug: hostvars verbosity=4

